Repository PSPDFKit/Cordova-Android, pull requests merged in 2019-06, with the labels that each got.

#47 Adds mention for documentation to README
  README.md
Labels: READY TO REVIEW

#46 Instant JSON API
  plugin.xml
  src/android/java/com/pspdfkit/cordova/CordovaPdfActivity.java
  src/android/java/com/pspdfkit/cordova/PSPDFKitCordovaPlugin.java
  src/android/java/com/pspdfkit/cordova/Utilities.java
  src/android/java/com/pspdfkit/cordova/action/Action.java
  src/android/java/com/pspdfkit/cordova/action/ActionManager.java
  src/android/java/com/pspdfkit/cordova/action/BasicAction.java
  src/android/java/com/pspdfkit/cordova/action/DismissAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/AddAnnotationAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/ApplyInstantJsonAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/GetAllUnsavedAnnotationsAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/GetAnnotationsAction.java
  src/android/java/com/pspdfkit/cordova/action/document/SaveDocumentAction.java
  src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentAction.java
  src/android/java/com/pspdfkit/cordova/action/document/ShowDocumentFromAssetsAction.java
  src/android/java/com/pspdfkit/cordova/event/EventDispatcher.java
  src/android/java/com/pspdfkit/cordova/provider/DocumentJsonDataProvider.java
  www/PSPDFKit.js
Labels: READY TO REVIEW, enhancement

#48 Instant JSON API: Remove annotation
  plugin.xml
  src/android/java/com/pspdfkit/cordova/PSPDFKitCordovaPlugin.java
  src/android/java/com/pspdfkit/cordova/Utilities.java
  src/android/java/com/pspdfkit/cordova/action/annotation/AddAnnotationAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/GetAnnotationsAction.java
  src/android/java/com/pspdfkit/cordova/action/annotation/RemoveAnnotationAction.java
  www/PSPDFKit.js
Labels: READY TO REVIEW, enhancement

#50 Update to PSPDFKit 5.4.1
  LICENSE
  package.json
  plugin.xml
  src/android/config.gradle
  src/android/java/com/pspdfkit/cordova/ExtractAssetTask.java
  src/android/java/com/pspdfkit/cordova/PSPDFKitCordovaPlugin.java
  src/android/java/com/pspdfkit/cordova/PSPDFKitCordovaPluginException.java
  src/android/pspdfkit.gradle
  tests/package.json
  tests/plugin.xml
  tests/tests.js
  www/PSPDFKit.js
Labels: READY TO REVIEW, update
